apiVersion: apps/v1
kind: Deployment
metadata:
  name: app1-winter-frontend-deployment
  labels:
    app: app1-winter-frontend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: app1-winter-frontend
  template:
    metadata:
      labels:
        app: app1-winter-frontend
        azure.workload.identity/use: "true"
    spec:
      serviceAccountName: workload-identity-sa
      containers:
        - name: app1-winter-frontend
          image: azurewinterproject.azurecr.io/kshitijkumarakswinterprojectfrontend
          ports:
            - containerPort: 80
          volumeMounts:
            - name: secrets-store01-inline
              mountPath: "/mnt/secrets-store"
              readOnly: true
      volumes:
        - name: secrets-store01-inline
          csi:
            driver: secrets-store.csi.k8s.io
            readOnly: true
            volumeAttributes:
              secretProviderClass: "azure-kvname-system-msi"