apiVersion: apps/v1
kind: Deployment
metadata:
  name: app1-winter-deployment
  labels:
    app: app1-winter
spec:
  replicas: 1
  selector:
    matchLabels:
      app: app1-winter
  template:
    metadata:
      labels:
        app: app1-winter
    spec:
      containers:
        - name: app1-winter
          image: azurewinterproject.azurecr.io/kshitijkumarakswinterprojectbackend
          ports:
            - containerPort: 80