apiVersion: v1
kind: Service
metadata:
  name: app1-winter-frontend-loadbalancer-service
  labels:
    app: app1-winter-frontend
spec:
  type: LoadBalancer
  selector:
    app: app1-winter-frontend
  ports:
    - port: 80
      targetPort: 3000