apiVersion: v1
kind: Service
metadata:
  name: app1-winter-frontend-clusterip-service
  labels:
    app: app1-winter-frontend
spec:
  type: ClusterIP
  selector:
    app: app1-winter-frontend
  ports:
    - port: 80
      targetPort: 80
